/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BiasRouteImport } from './routes/bias'
import { Route as IndexRouteImport } from './routes/index'

const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BiasRoute = BiasRouteImport.update({
  id: '/bias',
  path: '/bias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bias': typeof BiasRoute
  '/compare': typeof CompareRoute
  '/ethics': typeof EthicsRoute
  '/pipeline': typeof PipelineRoute
  '/screening': typeof ScreeningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bias': typeof BiasRoute
  '/compare': typeof CompareRoute
  '/ethics': typeof EthicsRoute
  '/pipeline': typeof PipelineRoute
  '/screening': typeof ScreeningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bias': typeof BiasRoute
  '/compare': typeof CompareRoute
  '/ethics': typeof EthicsRoute
  '/pipeline': typeof PipelineRoute
  '/screening': typeof ScreeningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bias' | '/compare' | '/ethics' | '/pipeline' | '/screening'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bias' | '/compare' | '/ethics' | '/pipeline' | '/screening'
  id:
    | '__root__'
    | '/'
    | '/bias'
    | '/compare'
    | '/ethics'
    | '/pipeline'
    | '/screening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiasRoute: typeof BiasRoute
  CompareRoute: typeof CompareRoute
  EthicsRoute: typeof EthicsRoute
  PipelineRoute: typeof PipelineRoute
  ScreeningRoute: typeof ScreeningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bias': {
      id: '/bias'
      path: '/bias'
      fullPath: '/bias'
      preLoaderRoute: typeof BiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiasRoute: BiasRoute,
  CompareRoute: CompareRoute,
  EthicsRoute: EthicsRoute,
  PipelineRoute: PipelineRoute,
  ScreeningRoute: ScreeningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
